version: '3.8'

networks:
  mynetwork:
    driver: bridge

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 4545
      POSTGRES_DB: online_course
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  app:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: 4545
      DB_NAME: online_course
    depends_on:
      - db
    ports:
      - "3000:3000"
    networks:
      - mynetwork
